### ISSUE TITLE
It looks like there is still nothing, am I missing something ?

### ISSUE THREAD

**Issue by LucaCoduriV** [BrianTiburcio/discord-rs#1]
I might be wrong, but there is no library yet.

**Comment by BrianTiburcio** [comment]
Nope! Apologies for any misconceptions. Mainly wanted to reserve the name on crates.io hence the premature push. The project is actively being worked on though, and will soon have a working version.

**Comment by BrianIAm** [comment]
> I might be wrong, but there is no library yet.

Nope! Apologies for any misconceptions. Mainly wanted to reserve the name on crates.io hence the premature push. The project is actively being worked on though, and will soon have a working version.
